#!/usr/bin/env bash

set -e

# Use MIST library
. mist/core.sh

# import catalog tools
. catalog/searchDomains.sh
. catalog/findOpenPorts.sh
. catalog/kafkaProducer.sh

FD_QUEUE="foundDomains"
FP_QUEUE="foundPorts"

# Cleanup queues after finishing
cleanup() {
    closeQueue $FD_QUEUE
    closeQueue $FP_QUEUE
}
trap cleanup EXIT ERR

# Create queues
openQueue $FD_QUEUE
openQueue $FP_QUEUE

# Launch workflows
searchDomains "germanramos.com" $FD_QUEUE &
findOpenPorts "80,443" $FD_QUEUE $FP_QUEUE &
kafkaProducer $KAFKA_SERVER "domainsTopic" $FP_QUEUE &

wait


# Simpler alternative using pipes
###searchDomains "germanramos.com" | findOpenPorts "80,443" | kafkaProducer $KAFKA_SERVER, $itegration_topic
