name: Generate docs for github pages

on:
  push:
    branches:
      - master
    paths:
      - "README.md"
      - "mist/lang/*.md"
      - ".github/workflows/gh-pages.yml"
      - ".github/build_doc.sh"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now

      - name: Build Documentation
        run: ./.github/build_doc.sh

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated_docs
          destination_dir: contents
          enable_jekyll: true
