name: Build Pypi Artifacts

on:
  create:
    tags:
      - v*

jobs:
  build-os:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          pip install setuptools wheel

      - name: Build distribution package
        run: |
          python setup.py sdist bdist_wheel

      - name: Save Pypi artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pypi
          path: dist/*

  deploy:
    name: Publish in Pypi
    needs: build-os
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          pip install twine

      - name: Recover Pypi artifacts
        uses: actions/download-artifact@v2
        with:
          name: pypi
          path: dist/

      - name: Listing artifacts
        run: ls dist/*

      - name: Publish Package Manager PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
